package org.firstinspires.ftc.teamcode.main.config;

public enum AutoState{
    INIT, MOVE_TO_SHOOTING_ZERO, SHOOTING_ZERO,
    MOVE_TO_FIRST_EAT, FINISH_FIRST_EAT,
    DROP_RAMP, MOVE_TO_SHOOTING_FIRST, SHOOTING_FIRST,
    MOVE_TO_SECOND_EAT, FINISH_SECOND_EAT, MOVE_TO_SHOOTING_SECOND, SHOOTING_SECOND,
    MOVE_TO_THIRD_EAT, FINISH_THIRD_EAT, MOVE_TO_SHOOTING_THIRD, SHOOTING_THIRD,
    LEAVE_FROM_ZONE, COMPLETE
}